// <auto-generated />
using System;
using System.Collections.Generic;
using CasaConSi.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CasaConSi.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260730000739_AddProfessionToApplicationUser")]
    partial class AddProfessionToApplicationUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CasaConSi.Api.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int?>("Generation")
                        .HasColumnType("integer");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CasaConSi.Api.Models.HostProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableRooms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedDni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedAmountRangeArs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("HomePhotoPaths")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("HousingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredTenantGeneration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PresentationMediaPath")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PreferredTenantGeneration");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("HostProfiles");
                });

            modelBuilder.Entity("CasaConSi.Api.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HostUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HostUserId");

                    b.HasIndex("StudentUserId", "HostUserId")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("CasaConSi.Api.Models.ProfileLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DecidedByRole")
                        .HasColumnType("integer");

                    b.Property<string>("HostUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Liked")
                        .HasColumnType("boolean");

                    b.Property<string>("StudentUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HostUserId");

                    b.HasIndex("StudentUserId", "HostUserId", "DecidedByRole")
                        .IsUnique();

                    b.ToTable("ProfileLikes");
                });

            modelBuilder.Entity("CasaConSi.Api.Models.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Amenities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("HostTypeLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HostUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PhotoPaths")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("PriceArs")
                        .HasColumnType("numeric");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("HostUserId");

                    b.HasIndex("Neighborhood");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("CasaConSi.Api.Models.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AvailableFrom")
                        .HasColumnType("date");

                    b.Property<string>("ContributionRangeArs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedDni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredHostGeneration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PreferredNeighborhoods")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("PresentationMediaPath")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("text");

                    b.Property<string>("StayDuration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PreferredHostGeneration");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CasaConSi.Api.Models.HostProfile", b =>
                {
                    b.HasOne("CasaConSi.Api.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("CasaConSi.Api.Models.HostProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.HostExchangesExpected", "ExchangesExpected", b1 =>
                        {
                            b1.Property<Guid>("HostProfileId");

                            b1.Property<string>("ExpectedAmountRangeArs")
                                .IsRequired();

                            b1.Property<string>("ExpectsMonthlyContribution")
                                .IsRequired();

                            b1.Property<string>("OtherExchangeDetail")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("OtherExchanges")
                                .IsRequired();

                            b1.HasKey("HostProfileId");

                            b1.ToTable("HostProfiles");

                            b1
                                .ToJson("ExchangesExpected")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HostProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.HostHabits", "Habits", b1 =>
                        {
                            b1.Property<Guid>("HostProfileId");

                            b1.Property<string>("BelongsToAssociation")
                                .IsRequired();

                            b1.Property<int>("CleanlinessExpectation");

                            b1.Property<string>("FreeTimeActivities")
                                .IsRequired();

                            b1.Property<string>("HasMinorChildrenAtHome")
                                .IsRequired();

                            b1.Property<string>("HasPets")
                                .IsRequired();

                            b1.Property<string>("MealPreference")
                                .IsRequired();

                            b1.Property<string>("PetsDetail")
                                .IsRequired();

                            b1.Property<string>("SmokesAtHome")
                                .IsRequired();

                            b1.Property<string>("VisitFrequency")
                                .IsRequired();

                            b1.HasKey("HostProfileId");

                            b1.ToTable("HostProfiles");

                            b1
                                .ToJson("Habits")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HostProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.HostHealth", "Health", b1 =>
                        {
                            b1.Property<Guid>("HostProfileId");

                            b1.Property<int>("CurrentHealthStatus");

                            b1.Property<string>("CurrentHelpDetail")
                                .IsRequired();

                            b1.Property<string>("DailyActivitySupportDetail")
                                .IsRequired();

                            b1.Property<string>("HasCurrentHelp")
                                .IsRequired();

                            b1.Property<string>("RelevantHealthCondition")
                                .IsRequired();

                            b1.Property<string>("TakesScheduledMedication")
                                .IsRequired();

                            b1.HasKey("HostProfileId");

                            b1.ToTable("HostProfiles");

                            b1
                                .ToJson("Health")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HostProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.HostHousingData", "HousingData", b1 =>
                        {
                            b1.Property<Guid>("HostProfileId");

                            b1.PrimitiveCollection<string>("Accessibility")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Amenities")
                                .IsRequired();

                            b1.Property<int>("AvailableRooms");

                            b1.Property<string>("FullAddress")
                                .IsRequired();

                            b1.Property<string>("HasPrivateBathroom")
                                .IsRequired();

                            b1.Property<string>("HousingType")
                                .IsRequired();

                            b1.Property<string>("Neighborhood")
                                .IsRequired();

                            b1.Property<string>("PublicTransportDistance")
                                .IsRequired();

                            b1.Property<int>("TotalBedrooms");

                            b1.HasKey("HostProfileId");

                            b1.ToTable("HostProfiles");

                            b1
                                .ToJson("HousingData")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HostProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.HostPersonalData", "PersonalData", b1 =>
                        {
                            b1.Property<Guid>("HostProfileId");

                            b1.Property<string>("BirthDate")
                                .IsRequired();

                            b1.Property<string>("ContactEmail")
                                .IsRequired();

                            b1.Property<string>("ContactPhone")
                                .IsRequired();

                            b1.Property<string>("FamilyReferenceName")
                                .IsRequired();

                            b1.Property<string>("FamilyReferencePhone")
                                .IsRequired();

                            b1.Property<string>("FamilyReferenceRelationship")
                                .IsRequired();

                            b1.Property<string>("FullName")
                                .IsRequired();

                            b1.Property<string>("Gender")
                                .IsRequired();

                            b1.Property<string>("MaritalStatus")
                                .IsRequired();

                            b1.HasKey("HostProfileId");

                            b1.ToTable("HostProfiles");

                            b1
                                .ToJson("PersonalData")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HostProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.HostPersonalPresentation", "PersonalPresentation", b1 =>
                        {
                            b1.Property<Guid>("HostProfileId");

                            b1.Property<string>("AboutMe")
                                .IsRequired();

                            b1.Property<string>("Motivation")
                                .IsRequired();

                            b1.HasKey("HostProfileId");

                            b1.ToTable("HostProfiles");

                            b1
                                .ToJson("PersonalPresentation")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HostProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.HostTenantPreferences", "TenantPreferences", b1 =>
                        {
                            b1.Property<Guid>("HostProfileId");

                            b1.Property<string>("AcceptsOtherNationality")
                                .IsRequired();

                            b1.Property<string>("AcceptsTenantChildrenVisiting")
                                .IsRequired();

                            b1.Property<string>("AcceptsTenantPets")
                                .IsRequired();

                            b1.Property<string>("AcceptsTenantSmoking")
                                .IsRequired();

                            b1.Property<string>("DealBreakers")
                                .IsRequired();

                            b1.Property<string>("NightCurfew")
                                .IsRequired();

                            b1.Property<string>("PreferredGeneration")
                                .IsRequired();

                            b1.Property<string>("PreferredTenantGender")
                                .IsRequired();

                            b1.Property<string>("TenantCanReceiveVisits")
                                .IsRequired();

                            b1.Property<string>("TenantCanStayAloneIfHostAway")
                                .IsRequired();

                            b1.HasKey("HostProfileId");

                            b1.ToTable("HostProfiles");

                            b1
                                .ToJson("TenantPreferences")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HostProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.HostWorkSituation", "WorkSituation", b1 =>
                        {
                            b1.Property<Guid>("HostProfileId");

                            b1.Property<string>("LivesAlone")
                                .IsRequired();

                            b1.Property<string>("OtherResidents")
                                .IsRequired();

                            b1.Property<string>("ProfessionOrEducation")
                                .IsRequired();

                            b1.Property<string>("WorkStatus")
                                .IsRequired();

                            b1.HasKey("HostProfileId");

                            b1.ToTable("HostProfiles");

                            b1
                                .ToJson("WorkSituation")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("HostProfileId");
                        });

                    b.Navigation("ExchangesExpected")
                        .IsRequired();

                    b.Navigation("Habits")
                        .IsRequired();

                    b.Navigation("Health")
                        .IsRequired();

                    b.Navigation("HousingData")
                        .IsRequired();

                    b.Navigation("PersonalData")
                        .IsRequired();

                    b.Navigation("PersonalPresentation")
                        .IsRequired();

                    b.Navigation("TenantPreferences")
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkSituation")
                        .IsRequired();
                });

            modelBuilder.Entity("CasaConSi.Api.Models.Match", b =>
                {
                    b.HasOne("CasaConSi.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasaConSi.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CasaConSi.Api.Models.ProfileLike", b =>
                {
                    b.HasOne("CasaConSi.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasaConSi.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CasaConSi.Api.Models.Space", b =>
                {
                    b.HasOne("CasaConSi.Api.Models.ApplicationUser", "Host")
                        .WithMany()
                        .HasForeignKey("HostUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Host");
                });

            modelBuilder.Entity("CasaConSi.Api.Models.StudentProfile", b =>
                {
                    b.HasOne("CasaConSi.Api.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("CasaConSi.Api.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.StudentEconomicSituation", "EconomicSituation", b1 =>
                        {
                            b1.Property<Guid>("StudentProfileId");

                            b1.Property<string>("CanPayMonthlyContribution")
                                .IsRequired();

                            b1.Property<string>("ContributionRangeArs")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("IncomeSources")
                                .IsRequired();

                            b1.Property<string>("MonthlyIncomeRange")
                                .IsRequired();

                            b1.HasKey("StudentProfileId");

                            b1.ToTable("StudentProfiles");

                            b1
                                .ToJson("EconomicSituation")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StudentProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.StudentExchangesOffered", "ExchangesOffered", b1 =>
                        {
                            b1.Property<Guid>("StudentProfileId");

                            b1.PrimitiveCollection<string>("Offerings")
                                .IsRequired();

                            b1.Property<string>("OtherOffering")
                                .IsRequired();

                            b1.HasKey("StudentProfileId");

                            b1.ToTable("StudentProfiles");

                            b1
                                .ToJson("ExchangesOffered")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StudentProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.StudentHabits", "Habits", b1 =>
                        {
                            b1.Property<Guid>("StudentProfileId");

                            b1.Property<int>("CleanlinessExpectation");

                            b1.Property<string>("CooksRegularly")
                                .IsRequired();

                            b1.Property<string>("HasChildrenAtHome")
                                .IsRequired();

                            b1.Property<string>("HasPets")
                                .IsRequired();

                            b1.Property<string>("MealPreference")
                                .IsRequired();

                            b1.Property<string>("PetsDetail")
                                .IsRequired();

                            b1.Property<string>("RelevantAllergies")
                                .IsRequired();

                            b1.Property<string>("Smokes")
                                .IsRequired();

                            b1.Property<string>("UsualScheduleBack")
                                .IsRequired();

                            b1.Property<string>("UsualScheduleOut")
                                .IsRequired();

                            b1.Property<string>("VisitFrequency")
                                .IsRequired();

                            b1.Property<string>("WeekendAbsenceFrequency")
                                .IsRequired();

                            b1.HasKey("StudentProfileId");

                            b1.ToTable("StudentProfiles");

                            b1
                                .ToJson("Habits")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StudentProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.StudentHealth", "Health", b1 =>
                        {
                            b1.Property<Guid>("StudentProfileId");

                            b1.Property<string>("DailySupportDetail")
                                .IsRequired();

                            b1.Property<string>("HealthCoverage")
                                .IsRequired();

                            b1.Property<string>("NeedsDailySupport")
                                .IsRequired();

                            b1.Property<string>("RelevantHealthCondition")
                                .IsRequired();

                            b1.HasKey("StudentProfileId");

                            b1.ToTable("StudentProfiles");

                            b1
                                .ToJson("Health")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StudentProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.StudentHostPreferences", "HostPreferences", b1 =>
                        {
                            b1.Property<Guid>("StudentProfileId");

                            b1.Property<string>("AcceptsCoupleHost")
                                .IsRequired();

                            b1.Property<string>("AcceptsHostChildren")
                                .IsRequired();

                            b1.Property<string>("AcceptsPetsAtHome")
                                .IsRequired();

                            b1.Property<string>("BotherIfHostSmokes")
                                .IsRequired();

                            b1.Property<string>("DealBreakers")
                                .IsRequired();

                            b1.Property<int>("OtherResidentsCount");

                            b1.Property<string>("PreferredGeneration")
                                .IsRequired();

                            b1.Property<string>("PreferredHostGender")
                                .IsRequired();

                            b1.HasKey("StudentProfileId");

                            b1.ToTable("StudentProfiles");

                            b1
                                .ToJson("HostPreferences")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StudentProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.StudentLocationPreferences", "LocationPreferences", b1 =>
                        {
                            b1.Property<Guid>("StudentProfileId");

                            b1.PrimitiveCollection<string>("ExcludedNeighborhoods")
                                .IsRequired();

                            b1.Property<string>("ExcludedNeighborhoodsOther")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("PreferredNeighborhoods")
                                .IsRequired();

                            b1.Property<string>("PreferredNeighborhoodsOther")
                                .IsRequired();

                            b1.Property<string>("ProximityNeeds")
                                .IsRequired();

                            b1.HasKey("StudentProfileId");

                            b1.ToTable("StudentProfiles");

                            b1
                                .ToJson("LocationPreferences")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StudentProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.StudentPersonalData", "PersonalData", b1 =>
                        {
                            b1.Property<Guid>("StudentProfileId");

                            b1.Property<string>("BirthDate")
                                .IsRequired();

                            b1.Property<string>("ContactEmail")
                                .IsRequired();

                            b1.Property<string>("ContactPhone")
                                .IsRequired();

                            b1.Property<string>("EmergencyContactName")
                                .IsRequired();

                            b1.Property<string>("EmergencyContactPhone")
                                .IsRequired();

                            b1.Property<string>("EmergencyContactRelationship")
                                .IsRequired();

                            b1.Property<string>("FullName")
                                .IsRequired();

                            b1.Property<string>("Gender")
                                .IsRequired();

                            b1.Property<string>("Nationality")
                                .IsRequired();

                            b1.HasKey("StudentProfileId");

                            b1.ToTable("StudentProfiles");

                            b1
                                .ToJson("PersonalData")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StudentProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.StudentPersonalPresentation", "PersonalPresentation", b1 =>
                        {
                            b1.Property<Guid>("StudentProfileId");

                            b1.Property<string>("AboutMe")
                                .IsRequired();

                            b1.Property<string>("Motivation")
                                .IsRequired();

                            b1.HasKey("StudentProfileId");

                            b1.ToTable("StudentProfiles");

                            b1
                                .ToJson("PersonalPresentation")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StudentProfileId");
                        });

                    b.OwnsOne("CasaConSi.Api.Models.Profiles.StudentTravelReason", "TravelReason", b1 =>
                        {
                            b1.Property<Guid>("StudentProfileId");

                            b1.Property<string>("AvailableFrom")
                                .IsRequired();

                            b1.Property<string>("Reason")
                                .IsRequired();

                            b1.Property<string>("ReasonOther")
                                .IsRequired();

                            b1.Property<string>("StayDuration")
                                .IsRequired();

                            b1.Property<string>("StudyDetails")
                                .IsRequired();

                            b1.Property<string>("WorkDetails")
                                .IsRequired();

                            b1.HasKey("StudentProfileId");

                            b1.ToTable("StudentProfiles");

                            b1
                                .ToJson("TravelReason")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StudentProfileId");
                        });

                    b.Navigation("EconomicSituation")
                        .IsRequired();

                    b.Navigation("ExchangesOffered")
                        .IsRequired();

                    b.Navigation("Habits")
                        .IsRequired();

                    b.Navigation("Health")
                        .IsRequired();

                    b.Navigation("HostPreferences")
                        .IsRequired();

                    b.Navigation("LocationPreferences")
                        .IsRequired();

                    b.Navigation("PersonalData")
                        .IsRequired();

                    b.Navigation("PersonalPresentation")
                        .IsRequired();

                    b.Navigation("TravelReason")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CasaConSi.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CasaConSi.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasaConSi.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CasaConSi.Api.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
